site_name: Thesis Notes and drafts
site_description: Notes from readings and other thesis writing
theme: readthedocs
dev_addr: '0.0.0.0:8000'
pages:
    - ['index.md', 'Index']
    - ['carver_proposal_draft_v4.md', 'Proposal Draft']
    - ['wittgenstein_PI_readers_guide.md', 'Notes for Philosophical Investgations readers guide']
    - ['keith-wittgenstein-notes.md', 'From Language Games to Forms of Life reading notes']
    - ['carver_outline_04082017.md', 'Initial Outline 04.08.2017']
    - ['cimcil_rethinking_PM_actuality.md', 'Rethinking Actuality reading notes']
    - ['enh-work_oriented_design_notes.md', 'Ehn - Work Oriented Design reading notes']
    - ['pleasants_wittgenstein_crit_theory.md', 'Pleasants - Wittgenstein and Critical Theory reading notes']
    - ['rethinking_communication_mckay.md', 'McKay - Rethinking Communication reading notes']
    - ['schatzki-bourdieu-giddens.md', 'Schatzki critique of Bourdieu Giddens reading notes']
    - ['johnson_ben_thesis_notes.md', 'Across the Divide: Reconciling Scrum and Enterprise with genre ecologies reading notes']
    - ['watson_practice_theory_notes.md', 'Watson Practice Theory reading notes']
    - ['conduit_metaphor_notes.md','Conduit Metaphor reading notes']
    - ['list_of_practices.md', 'List of Practices']
    - ['more_conduit_metaphor_notes.md', More Conduit Metaphor notes]
    - ['meeting_questions_notes.md', 'Meeting Questions and Notes']
