site_name: Thesis Notes and drafts
site_description: Notes from readings and other thesis writing
theme: mkdocs
pages:
    - ['index.md', 'Index']
    - ['carver_proposal_draft_v4.md', 'Proposal Draft']
